Update python-calci.yaml

diff --git a/.github/workflows/python-calci.yaml b/.github/workflows/python-calci.yaml
--- a/.github/workflows/python-calci.yaml
+++ b/.github/workflows/python-calci.yaml
@@ -89,7 +89,7 @@ jobs:
       run: cat report/report.json
 
     - name: Setup OPA
-      id: Steup
+      id: Setup
       run: |
         curl -L -o opa https://openpolicyagent.org/downloads/v0.46.1/opa_linux_amd64_static
         chmod 755 ./opa
@@ -99,5 +99,18 @@ jobs:
     - name: OPA check
       id: opa
       run: |  
-        opa eval --format json --data policies/unit.rego --input report/report.json "data.play" > opa_result.txt
+        opa eval --format json --data policies/unit.rego --input report/report.json "data.play" > opa_result.json
       continue-on-error: true
+
+    - name: Check OPA Result
+      id: opa_result
+      run: |
+        if grep -q '"allow": true' opa_result.json; then
+          echo "OPA check succeeded."
+        else
+          echo "OPA check failed. Exiting the pipeline."
+          exit 1
+        fi
+
+    - name: Run Python App
+      run: python Calculator.py
