Update python-calci.yaml

diff --git a/.github/workflows/python-calci.yaml b/.github/workflows/python-calci.yaml
--- a/.github/workflows/python-calci.yaml
+++ b/.github/workflows/python-calci.yaml
@@ -107,10 +107,11 @@ jobs:
       id: opa
       run: |  
         opa eval --format pretty --data policies/unit.rego --input report/report.json "data.play"
-        if [[ ${{ steps.opa.outputs.allow }} == 'false' ]]; then
-          echo "OPA check failed. Stopping the pipeline."
-          exit 1
+        if [[ "${{ steps.opa.outputs.allow }}" == "false" ]]; then
+         echo "OPA check failed. Stopping the pipeline."
+         exit 1
         fi
+
 
     - name: Run Python App
       run: python Calculator.py  # Adjust the command to run your Python application
